build:
  image: gbraad/minishift-build:latest
  script:
    - mkdir -p /workspace
    - ./bootstrap.sh
    - mv /workspace/src/github.com/minishift/minishift/out/ ./public
  artifacts:
    paths:
      - public
